services:
  obsidian:
    build: .
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - obsidian-files:/files
    networks:
      - bridge

volumes:
    obsidian-files:

networks:
  bridge:
    driver: bridge
    external: false